### PR TITLE
Secrets JSON build

### PR DESCRIPTION
**Pull request by bxjw**
Allows someone, such as a technologist, to build a local `secrets-sp.json` file via input prompts in terminal.

### CODE REVIEW

**Comment by bxjw** [comment]
```
        secrets = SecretsJSONFactory(args.name, EventSyncInputs)
        secrets.build_json()
        secrets.write_json()
```
should basically let someone create a secrets.json file that lets them run things using the secrets() context from this library. that way we have a 1:1 exact mapping from AWS secrets to the local secrets. this is also how [vote automation](https://github.com/stac-labs/vote-automation/blob/main/run_ga.py) and [event sync](https://github.com/stac-labs/van-event-sync/blob/main/demo.py) take in secrets as opposed to a .env file.

**Comment by bxjw** [comment]
Also goes along with this PR in event sync - https://github.com/stac-labs/van-event-sync/pull/24/files# - would let technologists make the secret without doing what I currently do, which is copy paste the secret as plaintext from AWS Secrets Manager to a json file for running on local. and it keeps the service account and whatnot formatted correctly, and will hopefully make it easier on less technical technologists.

**Comment by JulieGoldberg** [comment]
I think this works. But I'd argue strongly that [vote automation](https://github.com/stac-labs/vote-automation/blob/main/run_ga.py) and [event sync](https://github.com/stac-labs/van-event-sync/blob/main/demo.py) should be changed to use `.env` files and command-line arguments. And that's the approach we should train technologists on. If you're running things one-off, why would you make a file about how to run it before you run it? And if you're trying out a different parameter flag, why should you edit a json file rather than just sending a parameter?

**Comment by bxjw** [comment]
My reasons here:
1) The ability to copy paste back and forth with AWS secrets manager is really helpful for testing on local and then transferring to deployed with fewer errors
2) Technologists do have occasional one-offish things that they actually need to run 4 or 5 times
3) I think doing this may make building jsons a little less intimidating in general for technologists

**Comment by JulieGoldberg** [comment]
I totally agree on the ability to copy to & from AWS secrets. But a `.env` approach does the same. And it's only one file that presumably matches all states. Unless you have state-specific secrets that are actual secrets and not just settings? I agree that technologists often run things multiple times, and command-line arguments make that easy. I'm unsure why we want technologists to be less intimidated by building jsons. I do think encouraging them to be more familiar with command line work -- and including arguments to command-line scripts -- is beneficial. Whenever I tell someone to run a script, I always have them run it first with `-h` to ensure they know the potential arguments -- and to ensure that they have the requirements installed.

**Comment by jrose-stac** [comment]
I think we have to recognize that most of the time these scripts are going to run on AWS, and that we are not necessarily aiming for all technologists to be familiar with command line python all the time. Not everyone wants or needs that to be successful with what they're doing. Long term I think we need to meet people where they're at and if that's going to mean more retool for folks and less command line, that should be fine. If that means utilities like this, that should be fine too. 

A utility that helps them be able to run something locally once more efficiently without overhauling loads of our code to support either secrets or .env depending on how it is run seems fine to me.

**Review by JulieGoldberg — APPROVED** [review]

**Comment by bxjw** [comment]
yep that's what i was gonna say - they might have different service accounts, API keys, settings, etc. anyway thanks for the conversation all 😅

**Pull request merged**
